# default and development switch between  home and work
#home######################################################################
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see Rails configuration guide
#   # https://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   host: localhost
#   port: 5432

# development:
#   <<: *default
#   database: quote_editor_development
#   username: postgres
#   password: postgres
#work#######################################################################
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bmckibben
  password: C_satori22
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: projlog_development  
############################################################################  

test:
  <<: *default
  database: projlog_test

production:
  <<: *default
  database: projlog_production
  username: projlog
  password: <%= ENV["QUOTE_EDITOR_DATABASE_PASSWORD"] %>
